//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workman.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workman.Properties.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加日志 的本地化字符串。
        /// </summary>
        internal static string str_add_log {
            get {
                return ResourceManager.GetString("str_add_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string str_all {
            get {
                return ResourceManager.GetString("str_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序设置 的本地化字符串。
        /// </summary>
        internal static string str_app_setting {
            get {
                return ResourceManager.GetString("str_app_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启 的本地化字符串。
        /// </summary>
        internal static string str_auto_startup {
            get {
                return ResourceManager.GetString("str_auto_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string str_cancel {
            get {
                return ResourceManager.GetString("str_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string str_close {
            get {
                return ResourceManager.GetString("str_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string str_confirm {
            get {
                return ResourceManager.GetString("str_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string str_content {
            get {
                return ResourceManager.GetString("str_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string str_delete {
            get {
                return ResourceManager.GetString("str_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除行 的本地化字符串。
        /// </summary>
        internal static string str_delete_row {
            get {
                return ResourceManager.GetString("str_delete_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停靠 的本地化字符串。
        /// </summary>
        internal static string str_dock {
            get {
                return ResourceManager.GetString("str_dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停靠主屏 的本地化字符串。
        /// </summary>
        internal static string str_dock_main_screen {
            get {
                return ResourceManager.GetString("str_dock_main_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string str_edit {
            get {
                return ResourceManager.GetString("str_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗时 的本地化字符串。
        /// </summary>
        internal static string str_elapsed_time {
            get {
                return ResourceManager.GetString("str_elapsed_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止日期 的本地化字符串。
        /// </summary>
        internal static string str_end_date {
            get {
                return ResourceManager.GetString("str_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出程序 的本地化字符串。
        /// </summary>
        internal static string str_exit {
            get {
                return ResourceManager.GetString("str_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出日志 的本地化字符串。
        /// </summary>
        internal static string str_export_log {
            get {
                return ResourceManager.GetString("str_export_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string str_idx {
            get {
                return ResourceManager.GetString("str_idx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迭代 的本地化字符串。
        /// </summary>
        internal static string str_iteration {
            get {
                return ResourceManager.GetString("str_iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迭代管理 的本地化字符串。
        /// </summary>
        internal static string str_iteration_manage {
            get {
                return ResourceManager.GetString("str_iteration_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string str_name {
            get {
                return ResourceManager.GetString("str_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建迭代 的本地化字符串。
        /// </summary>
        internal static string str_new_iteration {
            get {
                return ResourceManager.GetString("str_new_iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增行 的本地化字符串。
        /// </summary>
        internal static string str_new_row {
            get {
                return ResourceManager.GetString("str_new_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建任务 的本地化字符串。
        /// </summary>
        internal static string str_new_task {
            get {
                return ResourceManager.GetString("str_new_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后一天 的本地化字符串。
        /// </summary>
        internal static string str_next_day {
            get {
                return ResourceManager.GetString("str_next_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开主界面 的本地化字符串。
        /// </summary>
        internal static string str_open_main_window {
            get {
                return ResourceManager.GetString("str_open_main_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string str_operation {
            get {
                return ResourceManager.GetString("str_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出目录 的本地化字符串。
        /// </summary>
        internal static string str_output {
            get {
                return ResourceManager.GetString("str_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前一天 的本地化字符串。
        /// </summary>
        internal static string str_prev_day {
            get {
                return ResourceManager.GetString("str_prev_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并关闭 的本地化字符串。
        /// </summary>
        internal static string str_save_and_close {
            get {
                return ResourceManager.GetString("str_save_and_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        internal static string str_start_date {
            get {
                return ResourceManager.GetString("str_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        internal static string str_task {
            get {
                return ResourceManager.GetString("str_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务数 的本地化字符串。
        /// </summary>
        internal static string str_task_count {
            get {
                return ResourceManager.GetString("str_task_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务管理 的本地化字符串。
        /// </summary>
        internal static string str_task_manage {
            get {
                return ResourceManager.GetString("str_task_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        internal static string str_today {
            get {
                return ResourceManager.GetString("str_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总耗时 的本地化字符串。
        /// </summary>
        internal static string str_total_elapsed_time {
            get {
                return ResourceManager.GetString("str_total_elapsed_time", resourceCulture);
            }
        }
    }
}
