// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workman.Infrastructure.DbContexts;

#nullable disable

namespace Workman.Infrastructure.Migrations
{
    [DbContext(typeof(WorkmanDbContext))]
    [Migration("20260309022949_AddContentField")]
    partial class AddContentField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Workman.Core.Entities.WorkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("f_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("f_content");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("f_date");

                    b.Property<float>("ElapsedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("f_elapsed_time");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("f_task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("wm_work_logs");
                });

            modelBuilder.Entity("Workman.Core.Entities.WorkProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("f_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("f_name");

                    b.HasKey("Id");

                    b.ToTable("wm_work_projects");
                });

            modelBuilder.Entity("Workman.Core.Entities.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("f_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("f_name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("f_project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("wm_work_tasks");
                });

            modelBuilder.Entity("Workman.Core.Entities.WorkLog", b =>
                {
                    b.HasOne("Workman.Core.Entities.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workman.Core.Entities.WorkTask", b =>
                {
                    b.HasOne("Workman.Core.Entities.WorkProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
